version: "3.7"

services:
    app:
        build:
            args:
                user: duque
                uid: 1000
            context: ./
            dockerfile: Dockerfile 
        image: sistema-veterinaria
        container_name: sistema-veterinaria-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - test-network 
    
    #No he pusto un puerto en este servicio
    db:
        image: mysql:5.7
        container_name: sistema-veterinaria-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
             - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - test-network
       
    nginx:
        image: nginx:1.17-alpine
        container_name: sistema-veterinaria-nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - test-network

    
networks:
    test-network:
        driver: bridge

volumes:
    dbdata:
